"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['twiOpinion.py']
DATA_FILES = ['guiConfiguration.py','guiCrawling.py','guiLearning.py','guiInfo.py',
                'config.py','readJson.py','versionControl.py', 'learningFunction.py', 'sklearnClassify.py',
                'infoFindEdge.py', 'infoTwitterGet.py']

OPTIONS = {'argv_emulation': True, 'iconfile': 'Spider.icns', 
            'packages' : ['tweepy', 'guess_language', 'nltk','pandas','sklearn', 'twitter']}
#OPTIONS = {'argv_emulation': True, 'iconfile': 'Spider.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
